require 'shelljs/global'

task 'run', 'run {{name}}', (options) ->
  require './server'

task 'test', 'test {{name}}', (options) ->
  exec 'node_modules/mocha/bin/mocha --compilers coffee:coffee-script test/* -R spec -t 5000 -c'
