// Generated by CoffeeScript 1.3.3
var fs, path, wrench;

fs = require('fs');

path = require('path');

wrench = require('wrench');

module.exports = function() {
  var dest, source, src;
  src = this.options["public"] || '.';
  dest = this.options.dist || 'dist/';
  wrench.rmdirSyncRecursive(dest, true);
  fs.mkdirSync(dest);
  wrench.copyDirSyncRecursive(src, dest);
  source = this.hemPackage().compile();
  fs.writeFileSync(path.join(dest, this.options.jsPath), source);
  source = this.cssPackage().compile();
  return fs.writeFileSync(path.join(dest, this.options.cssPath), source);
};
