// Generated by CoffeeScript 1.3.3
var fs, generatePath, minify, path, wrench;

fs = require('fs');

path = require('path');

wrench = require('wrench');

minify = require('./minify');

generatePath = function(orig, ext) {
  var out;
  out = path.basename(orig).split('.');
  out.pop();
  out.push(ext);
  return out.join('.');
};

module.exports = function(die) {
  var css, cssPath, dest, js, jsPath, source;
  dest = die.options.dist || 'dist/';
  js = die.options.main;
  css = die.options.css;
  jsPath = die.options.jsPath;
  cssPath = die.options.cssPath;
  wrench.rmdirSyncRecursive(dest, true);
  fs.mkdirSync(dest);
  if (path.existsSync(die.options["public"])) {
    wrench.copyDirSyncRecursive(die.options["public"], dest);
  }
  if (js) {
    if (!jsPath) {
      jsPath = generatePath(js, 'js');
    }
    source = die.jsPackage().compile();
    if (source) {
      if (die.options.minify) {
        source = minify.js(source);
      }
      fs.writeFileSync(path.join(dest, jsPath), source);
    }
  }
  if (css) {
    if (!cssPath) {
      cssPath = generatePath(css, 'css');
    }
    source = die.cssPackage().compile();
    if (source) {
      if (die.options.minify) {
        source = minify.css(source);
      }
      return fs.writeFileSync(path.join(dest, cssPath), source);
    }
  }
};
