// Generated by CoffeeScript 1.3.3
var die, path, pkg, program;

path = require('path');

program = require('commander');

die = require('./die');

pkg = require('../package.json');

program.version(pkg.version).usage('[command] [options]');

program.command('build').description('  assemble project').option('-o, --output [dir]').action(function(opts) {
  return die.build(opts);
});

program.command('new [name]').description('  create new project').usage('[name] [options]').option('-t, --template [name]', 'template to use').option('-c, --config [config.json]', 'configuration file to supply context variables from').action(function(name, opts) {
  return die.create(name, opts);
});

program.command('run').description('  serve project').option('-p, --port [number]', 'port to run server on').action(function(opts) {
  return die.run(opts);
});

program.command('test').description('  run tests').option('-a, --args [arguments]', 'arguments to pass to mocha').action(function(opts) {
  return die.test(opts);
});

program.command('watch').description('  watch for changes and rebuild project').action(function() {
  return die.watch();
});

program.parse(process.argv);
