// Generated by CoffeeScript 1.3.3

exports.jade = function(body, filename) {
  var func, jade;
  jade = require('jade');
  this.ignore(filename);
  func = jade.compile(body, {
    client: true,
    debug: false,
    compileDebug: false
  });
  return "module.exports = " + (func.toString());
};
