// Generated by CoffeeScript 1.3.3
var path;

path = require('path');

exports.defaults = require('./defaults');

exports.update = function(options, config) {
  var configPath, key, value;
  if (config == null) {
    config = 'defaults';
  }
  configPath = path.join(options.configPath, config);
  try {
    config = require(configPath);
    for (key in config) {
      value = config[key];
      options[key] = value;
    }
  } catch (error) {

  }
  options.paths.concat([path.dirname(options.main)]);
  return options;
};
