// Generated by CoffeeScript 1.3.3
var path;

path = require('path');

exports.defaults = require('./defaults');

exports.read = function(opts, config) {
  var key, val, _opts;
  if (!path.existsSync(config)) {
    config = path.join(opts.base, opts.configPath, config);
  }
  try {
    _opts = require(config);
    for (key in _opts) {
      val = _opts[key];
      opts[key] = val;
    }
  } catch (err) {

  }
  return opts;
};
