// Generated by CoffeeScript 1.3.3
var fs, mote, path, wrench;

fs = require('fs');

mote = require('mote');

path = require('path');

wrench = require('wrench');

module.exports = function(name, _arg, ctx) {
  var config, dest, file, filePath, key, src, template, val, _i, _len, _ref, _results;
  config = _arg.config, template = _arg.template;
  if (ctx == null) {
    ctx = {};
  }
  template = template || 'default';
  src = path.join(__dirname, '../templates', template);
  dest = name;
  ctx.name = path.basename(dest);
  ctx.user = process.env.USER;
  if (config) {
    for (key in config) {
      val = config[key];
      ctx[key] = val;
    }
  }
  if (path.existsSync(dest)) {
    return console.log("" + dest + " already exists.");
  }
  wrench.copyDirSyncRecursive(src, dest);
  _ref = wrench.readdirSyncRecursive(dest);
  _results = [];
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    file = _ref[_i];
    if (/^vendor/.test(file)) {
      continue;
    }
    filePath = path.join(dest, file);
    if (fs.statSync(filePath).isFile()) {
      template = mote.compile(fs.readFileSync(filePath).toString());
      _results.push(fs.writeFileSync(filePath, template(ctx)));
    } else {
      _results.push(void 0);
    }
  }
  return _results;
};
