// Generated by CoffeeScript 1.3.3
var argv, create, fs, milk, path, wrench;

fs = require('fs');

milk = require('milk');

path = require('path');

wrench = require('wrench');

argv = require('./cli').argv;

module.exports = create = function() {
  var ctx, dest, file, filePath, src, template, _i, _len, _ref, _results;
  template = argv.template || 'default';
  src = path.join(__dirname, '../templates', template);
  dest = argv._[1];
  ctx = argv.context || {};
  ctx.name = path.basename(dest);
  ctx.user = process.env.USER;
  wrench.copyDirSyncRecursive(src, dest);
  _ref = wrench.readdirSyncRecursive(dest);
  _results = [];
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    file = _ref[_i];
    if (/^vendor/.test(file)) {
      continue;
    }
    filePath = path.join(dest, file);
    if (fs.statSync(filePath).isFile()) {
      template = fs.readFileSync(filePath);
      _results.push(fs.writeFileSync(filePath, milk.render(template.toString(), ctx)));
    } else {
      _results.push(void 0);
    }
  }
  return _results;
};
