// Generated by CoffeeScript 1.3.3

module.exports = {
  configPath: '/config',
  buildPath: '/dist',
  staticPath: '/public',
  port: process.env.PORT || 3000,
  js: {
    main: '/client/js/app',
    url: '/app.js',
    libs: []
  },
  css: {
    main: '/client/css/app',
    url: '/app.css'
  }
};
