// Generated by CoffeeScript 1.3.3

module.exports = {
  configPath: 'config/',
  main: './client/js/app',
  jsPath: '/app.js',
  paths: ['./client/js'],
  dependencies: [],
  css: './client/css/app',
  cssPath: '/app.css',
  libs: [],
  "public": './public',
  port: process.env.PORT || 3000
};
