// Generated by CoffeeScript 1.3.3
var Die, build, compilers, config, pkg, server;

build = require('./build');

compilers = require('./compilers');

config = require('./config');

pkg = require('./package');

server = require('./server');

Die = (function() {

  function Die(options) {
    var key, val;
    if (options == null) {
      options = {};
    }
    for (key in options) {
      val = options[key];
      this.options[key] = val;
    }
    this.readConfig();
  }

  Die.prototype.options = config.defaults;

  Die.prototype.build = function() {
    this.readConfig('production');
    return build(this);
  };

  Die.prototype.compilers = compilers;

  Die.prototype.createServer = function() {
    return server(this);
  };

  Die.prototype.cssPackage = function() {
    return pkg.createCss(this.options.css);
  };

  Die.prototype.jsPackage = function() {
    return pkg.createJs({
      dependencies: this.options.dependencies,
      paths: this.options.paths,
      libs: this.options.libs
    });
  };

  Die.prototype.readConfig = function(name) {
    return this.options = config.readConfig(this.options, name);
  };

  return Die;

})();

module.exports = Die;
