// Generated by CoffeeScript 1.3.3
var Die, wrapper;

Die = require('./die');

wrapper = function(opts) {
  return new Die(opts);
};

wrapper.Die = Die;

wrapper.run = function() {
  return wrapper().run();
};

wrapper.build = function() {
  return wrapper().build();
};

wrapper.test = require('./test');

wrapper.version = require('../package.json').version;

module.exports = wrapper;
