// Generated by CoffeeScript 1.3.3
var Die, die, key, val, wrapper;

Die = require('./die');

die = new Die;

wrapper = function(cb) {
  var app;
  app = die.createServer();
  if (cb && cb.call) {
    cb.call(app);
  }
  return app;
};

for (key in die) {
  val = die[key];
  wrapper[key] = val;
}

module.exports = wrapper;
