// Generated by CoffeeScript 1.3.3

exports.js = function(source) {
  var ast, parser, uglify;
  parser = require('uglify-js').parser;
  uglify = require('uglify-js').uglify;
  ast = parser.parse(source);
  ast = uglify.ast_mangle(ast);
  ast = uglify.ast_squeeze(ast);
  return uglify.gen_code(ast);
};

exports.css = function(source) {
  return require('clean-css').process(source);
};
