// Generated by CoffeeScript 1.3.3
var exec, fs, path;

fs = require('fs');

path = require('path');

exec = require('./utils').exec;

module.exports = function(args) {
  var bin, nodePath;
  if (args == null) {
    args = '--compilers coffee:coffee-script -R spec -t 5000 -c';
  }
  if ((!path.existsSync('test')) || (fs.readdirSync('test').length === 0)) {
    return console.log('Tests not found.');
  }
  nodePath = process.env.NODE_PATH || '';
  process.env.NODE_PATH = "" + nodePath + ":";
  bin = 'node_modules/mocha/bin/mocha';
  if (!path.existsSync(bin)) {
    bin = 'mocha';
  }
  return exec("" + bin + " " + args);
};
