// Generated by CoffeeScript 1.3.3
var exec, path;

exec = require('child_process').exec;

path = require('path');

module.exports = function(args) {
  var bin, nodePath;
  if (args == null) {
    args = '--compilers coffee:coffee-script -R spec -t 5000 -c';
  }
  nodePath = process.env.NODE_PATH || '';
  process.env.NODE_PATH = "" + nodePath + ":";
  bin = 'node_modules/mocha/bin/mocha';
  if (!path.existsSync(bin)) {
    bin = 'mocha';
  }
  return exec("" + bin + " " + args, function(err, stdout, stderr) {
    console.log(stdout);
    return console.error(stderr);
  });
};
