// Generated by CoffeeScript 1.3.3
var exec, flatten;

exec = require('child_process').exec;

exports.flatten = flatten = function(array, results) {
  var item, _i, _len;
  if (results == null) {
    results = [];
  }
  for (_i = 0, _len = array.length; _i < _len; _i++) {
    item = array[_i];
    if (Array.isArray(item)) {
      flatten(item, results);
    } else {
      results.push(item);
    }
  }
  return results;
};

exports.toArray = function(value) {
  if (value == null) {
    value = [];
  }
  if (Array.isArray(value)) {
    return value;
  } else {
    return [value];
  }
};

exports.exec = function(args) {
  return exec(args, function(err, stdout, stderr) {
    console.log(stdout);
    return console.error(stderr);
  });
};

exports.getEncoding = function(buffer) {
  var charCode, contentStartBinary, contentStartUTF8, encoding, i, _i, _ref;
  contentStartBinary = buffer.toString('binary', 0, 24);
  contentStartUTF8 = buffer.toString('utf8', 0, 24);
  encoding = 'utf8';
  for (i = _i = 0, _ref = contentStartUTF8.length; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
    charCode = contentStartUTF8.charCodeAt(i);
    if (charCode === 65533 || charCode <= 8) {
      encoding = 'binary';
      break;
    }
  }
  return encoding;
};
