// Generated by CoffeeScript 1.3.3
var dirname, existsSync, join, _ref,
  __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

_ref = require('path'), dirname = _ref.dirname, existsSync = _ref.existsSync, join = _ref.join;

module.exports = function(die) {
  var base, css, dir, js, lib, watch, _i, _j, _k, _len, _len1, _len2, _ref1, _ref2, _ref3, _ref4, _ref5, _results,
    _this = this;
  base = die.options.base;
  watch = [];
  die.build();
  _ref1 = (function() {
    var _j, _len, _ref1, _ref2, _ref3, _results;
    _ref3 = ((_ref1 = die.options) != null ? (_ref2 = _ref1.js) != null ? _ref2.libs : void 0 : void 0) || [];
    _results = [];
    for (_j = 0, _len = _ref3.length; _j < _len; _j++) {
      lib = _ref3[_j];
      _results.push(dirname(join(base, lib)));
    }
    return _results;
  })();
  for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
    dir = _ref1[_i];
    if (__indexOf.call(watch, dir) < 0) {
      watch.push(dir);
    }
  }
  js = (_ref2 = die.options) != null ? (_ref3 = _ref2.js) != null ? _ref3.main : void 0 : void 0;
  css = (_ref4 = die.options) != null ? (_ref5 = _ref4.css) != null ? _ref5.main : void 0 : void 0;
  if (js) {
    watch.push(dirname(join(base, js)));
  }
  if (css) {
    watch.push(dirname(join(base, css)));
  }
  for (_j = 0, _len1 = watch.length; _j < _len1; _j++) {
    dir = watch[_j];
    if (!existsSync(dir)) {
      continue;
    }
    require('watch').watchTree(dir, function(file, curr, prev) {
      if (curr && (curr.nlink === 0 || +curr.mtime !== +(prev != null ? prev.mtime : void 0))) {
        console.log("" + file + " changed.  Rebuilding.");
        return die.build();
      }
    });
  }
  console.log('watching:');
  _results = [];
  for (_k = 0, _len2 = watch.length; _k < _len2; _k++) {
    dir = watch[_k];
    _results.push(console.log("    " + dir));
  }
  return _results;
};
