// Generated by CoffeeScript 1.3.3
var compilers, path,
  __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

compilers = require('./compilers');

path = require('path');

module.exports = function(die) {
  var dir, lib, watched, _i, _len, _ref, _ref1, _results,
    _this = this;
  watched = [];
  die.build();
  _ref = ((function() {
    var _j, _len, _ref, _results1;
    _ref = die.options.libs;
    _results1 = [];
    for (_j = 0, _len = _ref.length; _j < _len; _j++) {
      lib = _ref[_j];
      _results1.push(path.dirname(lib));
    }
    return _results1;
  })()).concat(die.options.css, die.options.paths);
  _results = [];
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    dir = _ref[_i];
    if (_ref1 = !dir, __indexOf.call(watched, _ref1) < 0) {
      continue;
    }
    if (!path.existsSync(dir)) {
      continue;
    }
    watched.push(dir);
    console.log(dir);
    _results.push(require('watch').watchTree(dir, function(file, curr, prev) {
      if (curr && (curr.nlink === 0 || +curr.mtime !== +(prev != null ? prev.mtime : void 0))) {
        console.log("" + file + " changed.  Rebuilding.");
        return die.build();
      }
    }));
  }
  return _results;
};
